### ISSUE TITLE
macOS: Alacritty enters two keys per key repeat

### ISSUE THREAD

**Issue by jerrykal** [alacritty/alacritty#1375]
> Which operating system does the issue occur on? `macOS High Sierra 10.13.5`

For example, when you hold down a key (e.g. <kbd>j</kbd>), the key repeating rate is much faster than usual; and it seems like the problem is happening after [this commit](https://github.com/jwilm/alacritty/commit/765949f256aefcc513d0bfb46b64d315f9c2f3d2).

**Comment by chrisduerr** [comment]
Define "faster than usual"? Unless it's repeating at an unusable level I don't think this is an issue?

Could you maybe share an video/gif comparison of before and after? Unfortunately I'm not able to test on macos.

**Comment by E5ten** [comment]
I'm currently stuck on macos and it seems normal to me, definitely not unusable.

**Comment by nixpulvis** [comment]
It's funny back when I used a mac I had a script that made my keystrokes faster globally. But I'd expect that alacritty should be the same as everywhere else.

**Comment by ooJerryLeeoo** [comment]
@chrisduerr Here's a few rough examples of the key repeating rates:

> Key repeating rate in Alacritty [765949f256aefcc513d0bfb46b64d315f9c2f3d2]

![kapture 2018-06-14 at 23 25 08](https://user-images.githubusercontent.com/20783502/41422696-0f8cee58-702c-11e8-9411-5c465ad9d019.gif)

> Key repeating rate in Alacritty [f7172fd6e7a7eb1444007030efa39f2f21558342]

![kapture 2018-06-14 at 23 44 20](https://user-images.githubusercontent.com/20783502/41423061-f1b056b2-702c-11e8-81f3-6d8483e385ed.gif)

> Key repeating rate in iTerm2

![kapture 2018-06-14 at 23 27 01](https://user-images.githubusercontent.com/20783502/41422613-d446cc24-702b-11e8-990c-c123c7254a96.gif)

As shown in the gifs above, the key repeating rate of the first gif is faster than the others.

**Comment by jwilm** [comment]
@ooJerryLeeoo what is your key repeat rate configured for? I believe there was some artificial limiting being imposed under earlier versions of winit, and it's possible that's been resolved.

**Comment by ooJerryLeeoo** [comment]
@jwilm I've set `Key Repeat` to `Fast` and `Delay Until Repeat` to `Short`:

<img width="780" alt="screen shot 2018-06-15 at 6 38 48 am" src="https://user-images.githubusercontent.com/20783502/41441806-cb751e62-7066-11e8-841a-01f76e807267.png">

**Comment by ooJerryLeeoo** [comment]
@jwilm It's weird that the key repeating rate of keys like <kbd>Tab</kbd> , <kbd>Return</kbd> and arrow keys are normal

**Comment by ooJerryLeeoo** [comment]
I've figured out the real cause of the problem is that Alacritty somehow enters two characters per key repeat, which explains why the key repeating rate under Alacritty is about twice as faster.

For example, if I slow down my mac's key repeating rate, and do the same key repeat test under Alacritty, I can see that it enters two characters every key repeat:

![kapture 2018-06-15 at 9 33 26](https://user-images.githubusercontent.com/20783502/41445950-6651dc78-707f-11e8-8b4c-85486592bf59.gif)

**Comment by chrisduerr** [comment]
I've tagged this as winit because I'm pretty sure we don't do anything related to this kind of stuff ourselves? @francesca64 do you know about any issue like that?

**Comment by francesca64** [comment]
> I'm pretty sure we don't do anything related to this kind of stuff ourselves? 

I'm quite sure, since winit's keyboard API isn't rich enough for you to handle repeats at all.

The way we generate `ReceivedCharacter` for key repeats is a hack: https://github.com/tomaka/winit/blob/1b74822cfc0cb7fba4ed4940a3faae9499fcda95/src/platform/macos/view.rs#L386-L399

From what I observed, repeats don't trigger `insertText`, so without that hack repeats generate no characters at all. I'm not sure why they'd be doubled up, unless either A) `insertText` is triggered in some environments, or B) `doCommandBySelector` is triggered.

Though, there's also C) `last_insert` contains the character twice, which would definitely be the most amusing outcome. All of these cases are trivially easy to debug, too.

This is probably a great first-time issue if anyone wants to take a crack at it. In the likely scenario that nobody does, I'll probably be able to get to this tomorrow.

**Comment by chrisduerr** [comment]
Thanks for jumping to my help so quickly. Seems like there are some great possible solutions lined up ready to be tested. :+1:

**Comment by francesca64** [comment]
Okay, this is really *something*.

This only happens for some keys. For instance, A. It doesn't happen with B. Some keys inexplicably trigger `insertText` when held, while others inexplicably don't.

Fortunately, I was able to make a trivial fix by circumventing the inconsistency: tomaka/winit#570

Does anyone have any idea why this discrepancy exists? It seems really weird.

**Comment by garyemerson** [comment]
@francesca64, could this be related to the macOS feature where holding down some keys create a popup with accented character options? I know I've run into key repeat problems in the past due to this feature being enabled.

After holding down some keys in TextEdit looks like a,e,i,o,u should invoke a popup but b,t,r,x,m should not which matches your A but not B conundrum.

The official name for the setting is `ApplePressAndHoldEnabled` so you can check whether it's enable with:
```
defaults read NSGlobalDomain ApplePressAndHoldEnabled
```

And if it happens to be disabled you can enable it with:
```
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool true
```

**Comment by chrisduerr** [comment]
@garyemerson I believe the issue has already been resolved in https://github.com/tomaka/winit/pull/628. If you try out #1403, it should already solve this problem.

I'd love to confirm if this is solved with the glutin PR. Please let me know if you give it a shot!

**Comment by trimental** [comment]
@chrisduerr perhaps you made a mistake as https://github.com/tomaka/winit/pull/628 PR only effects wayland and not macos?

**Comment by francesca64** [comment]
@chrisduerr I believe this was resolved with tomaka/winit#570; @garyemerson is addressing my curiosity on why this happened inconsistently.

@garyemerson thanks for getting to the bottom of this! I'll update the [comment](https://github.com/tomaka/winit/blob/a70bc2082908a189d613f42534c9f39fd7df572f/src/platform/macos/view.rs#L401) accordingly.

**Comment by chrisduerr** [comment]
Oh thanks a lot for the update @francesca64. So @garyemerson if you're able to confirm that this has been fixed in the #1403 PR, that would help a lot.

I'll add it to the auto-close queue of that PR once someone can confirm if this has been solved.

**Comment by daGrevis** [comment]
Hmm, I'm still experiencing this on latest `master`.

Running `defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool true` fixed it for `j` key, but problem still persists for `k` key.

**Comment by arooni** [comment]
I have found that holding down a single key on Mac works well (j or k) but if trying control + e or control + y in nvim there is *absolutely no* repeat at all.

**Comment by cfal** [comment]
I can reproduce this every time on alacritty built at a425fe6bfe734bb80dce334d6f1c53e0bd41c0db on MacOS 10.15.4 on the tmux session screen (Ctrl-B, S), and pressing up and down. It's impossible to select every other row because it always goes up or down two rows at a time on a single key press. Other terminals (iTerm, kitty) do not have this problem.

**Comment by kchibisov** [comment]
@cfal remove old bindings you haven't defined yourself.

**Comment by cfal** [comment]
@kchibisov Thanks, that fixed it

**Comment by lonelykid** [comment]
I have not try combined keys repeating. But you do have to consider disabling ApplePressAndHoldEnabled. I have problems repeating hjkl in vim in alacritty. I spent some time thinking about how to disable the feature for vim. Then I realized it is  alacritty that handles key repeating. iTerm works out of the box. Not sure how they achieved this.

> I can reproduce this every time on alacritty built at [a425fe6](https://github.com/alacritty/alacritty/commit/a425fe6bfe734bb80dce334d6f1c53e0bd41c0db) on MacOS 10.15.4 on the tmux session screen (Ctrl-B, S), and pressing up and down. It's impossible to select every other row because it always goes up or down two rows at a time on a single key press. Other terminals (iTerm, kitty) do not have this problem.

**Comment by kchibisov** [comment]
This is long fixed iirc.
