### ISSUE TITLE
fails to install from git

### ISSUE THREAD

**Issue by matthiaskrgr** [alacritty/alacritty#2378]
`cargo install --git https://github.com/jwilm/alacritty/  --force `
````
    Updating git repository `https://github.com/jwilm/alacritty/`
  Installing alacritty v0.3.2 (https://github.com/jwilm/alacritty/#37b66a7c)
    Updating crates.io index
error: failed to compile `alacritty v0.3.2 (https://github.com/jwilm/alacritty/#37b66a7c)`, intermediate artifacts can be found at `/tmp/cargo-installnMe4iJ`

Caused by:
  multiple packages link to native library `freetype`, but a native library can be linked only once

package `freetype-sys v0.7.1`
    ... which is depended on by `freetype-rs v0.19.1`
    ... which is depended on by `font v0.1.0 (https://github.com/jwilm/alacritty/#37b66a7c)`
    ... which is depended on by `alacritty_terminal v0.3.2 (https://github.com/jwilm/alacritty/#37b66a7c)`
    ... which is depended on by `alacritty v0.3.2 (https://github.com/jwilm/alacritty/#37b66a7c)`
links to native library `freetype`

package `servo-freetype-sys v4.0.3`
    ... which is depended on by `servo-fontconfig-sys v4.0.7`
    ... which is depended on by `servo-fontconfig v0.4.0`
    ... which is depended on by `font v0.1.0 (https://github.com/jwilm/alacritty/#37b66a7c)`
    ... which is depended on by `alacritty_terminal v0.3.2 (https://github.com/jwilm/alacritty/#37b66a7c)`
    ... which is depended on by `alacritty v0.3.2 (https://github.com/jwilm/alacritty/#37b66a7c)`
also links to native library `freetype`
````

Running `cargo build --release` in the repo does not show the failure though. :thinking:

**Comment by chrisduerr** [comment]
That seems like a very odd issue, maybe `cargo install` is not workspace-aware?

**Comment by NickeZ** [comment]
I have an issue that I think is related. I've always installed alacritty with `cargo install -f --path .` but that doesn't work any more:

```
error: found a virtual manifest at `/home/niklas/git/alacritty/Cargo.toml` instead of a package manifest
```

I can only guess that I should go into maybe alacritty_terminal and try from there instead. Didn't try it yet.

**Comment by chrisduerr** [comment]
You can use `--path alacritty` to install it when you have the source folder available. Just `cargo install -f` should work too I think, though I believe that's deprecated?

This isn't a problem though, since it still works. But with git there doesn't seem to be a way to make it work.

**Comment by NickeZ** [comment]
maybe you can supply both `--path` and `--git`. Not using path has become an "error" so it will fail. It was a warning for a while.

**Comment by chrisduerr** [comment]
You can't supply `--path` unless you're installing from a local directory. I've tested both `--path` and `--bin` to no avail.

**Comment by nixpulvis** [comment]
@NickeZ see the referenced issue in rust-lang/cargo above.

**Comment by NickeZ** [comment]
Yeah I missed it but found it by myself while searching the cargo issue tracker. Both cargo and rustup could definitely benefit from some more attention

**Comment by gvoysey** [comment]
this is still happening: 
# Which operating system does the issue occur on?
Ubuntu 16.04.6
# If on linux, are you using X11 or Wayland?
x11
# rust/rustc
rustc 1.37.0 (eae3437df 2019-08-13)
rustup 1.18.3 (435397f48 2019-05-22)
# Steps to recreate
```
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
cargo install --git https://github.com/jwilm/alacritty/ --force
```
# result
```
Updating git repository `https://github.com/jwilm/alacritty/`
  Installing alacritty v0.3.3 (https://github.com/jwilm/alacritty/#db63c315)
    Updating crates.io index
  Downloaded clap v2.33.0
... (eliding a bunch of junk here)
  Downloaded rand_chacha v0.1.1
error: failed to compile `alacritty v0.3.3 (https://github.com/jwilm/alacritty/#db63c315)`, intermediate artifacts can be found at `/tmp/cargo-install6iGvpA`

Caused by:
  multiple packages link to native library `freetype`, but a native library can be linked only once

package `freetype-sys v0.7.1`
    ... which is depended on by `freetype-rs v0.19.1`
    ... which is depended on by `font v0.1.0 (https://github.com/jwilm/alacritty/#db63c315)`
    ... which is depended on by `alacritty_terminal v0.3.3 (https://github.com/jwilm/alacritty/#db63c315)`
    ... which is depended on by `alacritty v0.3.3 (https://github.com/jwilm/alacritty/#db63c315)`
links to native library `freetype`

package `servo-freetype-sys v4.0.3`
    ... which is depended on by `servo-fontconfig-sys v4.0.7`
    ... which is depended on by `servo-fontconfig v0.4.0`
    ... which is depended on by `font v0.1.0 (https://github.com/jwilm/alacritty/#db63c315)`
    ... which is depended on by `alacritty_terminal v0.3.3 (https://github.com/jwilm/alacritty/#db63c315)`
    ... which is depended on by `alacritty v0.3.3 (https://github.com/jwilm/alacritty/#db63c315)`
also links to native library `freetype`
```

**Comment by petr-tik** [comment]
Thanks for the awesome terminal application. Unfortunately, I cannot build it either. 

Info on system and alacritty version below - hope this helps. 

```bash
$$$ rustc -V
rustc 1.38.0 (625451e37 2019-09-23)
$$$ cargo -V
cargo 1.38.0 (23ef9a4ef 2019-08-20)
$$$ RUSTC_WRAPPER= cargo install --git https://github.com/jwilm/alacritty/ --force
    Updating git repository `https://github.com/jwilm/alacritty/`
  Installing alacritty v0.3.3 (https://github.com/jwilm/alacritty/#a75e9493)
    Updating crates.io index
    Updating git repository `https://github.com/chrisduerr/glutin`
    Updating git repository `https://github.com/rust-windowing/winit`
error: failed to compile `alacritty v0.3.3 (https://github.com/jwilm/alacritty/#a75e9493)`, intermediate artifacts can be found at `/tmp/cargo-installHDYMKC`

Caused by:
  multiple packages link to native library `freetype`, but a native library can be linked only once

package `freetype-sys v0.7.1`
    ... which is depended on by `freetype-rs v0.19.1`
    ... which is depended on by `font v0.1.0 (https://github.com/jwilm/alacritty/#a75e9493)`
    ... which is depended on by `alacritty v0.3.3 (https://github.com/jwilm/alacritty/#a75e9493)`
links to native library `freetype`

package `servo-freetype-sys v4.0.3`
    ... which is depended on by `servo-fontconfig-sys v4.0.7`
    ... which is depended on by `servo-fontconfig v0.4.0`
    ... which is depended on by `font v0.1.0 (https://github.com/jwilm/alacritty/#a75e9493)`
    ... which is depended on by `alacritty v0.3.3 (https://github.com/jwilm/alacritty/#a75e9493)`
also links to native library `freetype`
$$$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
$$$ uname -ar
Linux merluza 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$$$ cat /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 8
model name	: AMD Ryzen Threadripper 2920X 12-Core Processor
```

**Comment by chrisduerr** [comment]
This is a problem with cargo, if you run into this, please just clone Alacritty manually and install from inside the repo.

**Comment by petr-tik** [comment]
> This is a problem with cargo, if you run into this, please just clone Alacritty manually and install from inside the repo.

should have said in my original comment - that's exactly what I did and it worked great. 

thanks for addressing this

**Comment by chrisduerr** [comment]
Looks like someone has fixed this in cargo: https://github.com/rust-lang/cargo/pull/7768.

**Comment by matthiaskrgr** [comment]
Could we keep the ticket open until the fix lands in stable? (it's not even on nightly yet)

**Comment by chrisduerr** [comment]
I'm not fond of keeping track of when exactly things are stabilized. The bug has been fixed and people interested in installing through git can use nightly until it works in stable. Alacritty's issue tracker isn't here to keep track of Rust feature stabilizations and it would be quite difficult to do that. So I'd rather close this now and be done with it rather than keeping it open for no purpose and forgetting about it.

**Comment by matthiaskrgr** [comment]
Ok.
I was just disappointed when I saw the ticket was closed but I could still not `cargo install --git` alacritty .. :/
