### ISSUE TITLE
Crashes on start on Windows

### ISSUE THREAD

**Issue by Number7tSeven** [alacritty/alacritty#3177]
After installing the latest version, Alacritty crashes on start with an error pop-up. I've tried running it with and without a config file but no luck. Any ideas?

### System

OS: Windows 10
Version: 0.4.1 (installed via msi installer)
Windows: ConPTY

#### Alacritty: Runtime Error
panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', C:\Users\travis\.cargo\git\checkouts\winit-c2fdb27092aba5a7\d1c6506\src\platform_impl\windows\dark_mode.rs:135:13

**Comment by kchibisov** [comment]
@davidhewitt

**Comment by kchibisov** [comment]
The crash is outside of alacritty as far as I can see, so it's a winit bug.

**Comment by davidhewitt** [comment]
That's a file I helped with in winit so I'll help figure this one out.

@Number7tSeven what Windows 10 version are you running? (e.g. Insiders Fast Ring, October 2018 update, etc)

**Comment by Number7tSeven** [comment]
I see. Since the error seems to have something to do with winit's handling of Windows dark mode I tried it with light mode but with no luck. I still get the same error.

**Comment by Number7tSeven** [comment]
I am running October 2018 update (1809).

**Comment by chrisduerr** [comment]
Probably a good idea to try and update.

**Comment by kchibisov** [comment]
I think old Windows should also work in this case tbh, so if winit crashes on some old windows(2018 isn't that old tbh), so it's a bug, I guess.

**Comment by davidhewitt** [comment]
We tested the patch on several OS versions and were satisfied that it worked correctly from April 2018 update onwards iirc.

I'll have another read through and @Number7tSeven may come back with a patch that I'll ask you to try (if I can't get an old vm running)

**Comment by Number7tSeven** [comment]
Thanks. I can understand if you don't want to support older versions of Windows though.

**Comment by davidhewitt** [comment]
:+1: will see what I can find later when I investigate

**Comment by chrisduerr** [comment]
The release is still officially supported by Windows (see https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet), both for Home and Enterprise users. So Alacritty should definitely work on it.

**Comment by davidhewitt** [comment]
Apologies for the delay on this. I just now found time to set up a VM running Windows 10 October 2018. Two interesting things to note:

-  I can reproduce this crash on a fresh install of Windows 10 October 2018 (build number `10.0.17763.1`, according to the welcome message in `cmd.exe`).

- If I use windows update to install all security updates (_but not upgrade to March 2019 or November 2019_), then this crash no longer occurs. `cmd.exe` shows build number `10.0.17763.973` after all these updates are installed.

So @Number7tSeven I recommend that if you install a few updates, Alacritty will start working. You don't have to upgrade your Windows OS version, just a few recommended patches :)

Given that my conclusion is that a properly patched Windows 10 October 2018 is supported, I'm reluctant to attempt to create a patch to fix the crashing build.

**Comment by chrisduerr** [comment]
> Given that my conclusion is that a properly patched Windows 10 October 2018 is supported, I'm reluctant to attempt to create a patch to fix the crashing build.

Since Alacritty supports only the latest supported version of Windows, we do not support running outdated versions of the operating system and such configurations are not recommended.

**Comment by foisonocean** [comment]
I'm running Windows 10 Enterprise LTSC 1809 and got the same problem. It is the latest version of Windows in LTSC channel so it couldn't be upgraded.
Since 1809 is the latest version in LTSC channel, I think it should be supported.

**Comment by chrisduerr** [comment]
This should be fixed in the next release, we just need to wait for another version of our winit depedency.

**Comment by chrisduerr** [comment]
Could someone check if this is fixed on the latest master? An upstream PR was merged to fix Windows 7/8, but it might not have fixed this specific crash.

**Comment by Number7tSeven** [comment]
@chrisduerr, I built it and I am still getting the same error on my machine that I originally posted about.

**Comment by chrisduerr** [comment]
Fixed upstream in https://github.com/rust-windowing/winit/pull/1459.

**Comment by Number7tSeven** [comment]
@chrisduerr I would test this but I am a noob and am having difficulty building this. Is there a straightforward way to get Cargo to build using your experimental branch of Winit?

**Comment by chrisduerr** [comment]
You just have to apply the following patch to Alacritty:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 415ceb9..67d8b03 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -13,3 +13,4 @@ incremental = false
 
 [patch.crates-io]
 servo-freetype-sys = { path = "servo-freetype-proxy" }
+winit = { git = "https://github.com/chrisduerr/winit", branch = "fix-windows-assert" }
```

Just put that into a file and run `git apply <file>`, or since it's just a single line you can also apply it easily by hand.

Thanks for helping out with testing, it's much appreciated. :)

**Comment by Number7tSeven** [comment]
It was the Cargo part that was tripping me up. I will have to do a little research on my own.

I've built it and Alacritty seems to be working like normal. Thank you for all of your effort!

**Comment by Number7tSeven** [comment]
@chrisduerr After playing around with build using your fix I have encountered another bug. When I have an instance of Alacritty open and I lock windows, Alacritty will crash upon unlocking Windows.

Error output:
```
panicked at 'redraw event in non-redraw phase', C:\Users\username\.cargo\git\checkouts\winit-081229dbb0c89e9b\286e8ef\src\platform_impl\windows\event_loop\runner.rs:427:17
panicked at 'already borrowed: BorrowMutError', src\libcore\result.rs:1188:5
thread panicked while processing panic. aborting.
```

I don't recall this happening before. I just thought I would let you know. Let me know if this should be a separate issue.

**Comment by kchibisov** [comment]
It's a known issue https://github.com/rust-windowing/winit/issues/1466.

**Comment by Number7tSeven** [comment]
My apologies. I should have checked there first.
