### ISSUE TITLE
Alacritty resizes itself to be 4x2

### ISSUE THREAD

**Issue by dave-tucker** [alacritty/alacritty#5647]
When starting `alacritty` on my system, it used to open in a sensible sized window.
However, today it seems to have decided to resize itself to 4x2 :scream: 

Launching Alacritty from KDE Plasma and attempting to resize results in `free(): invalid next size (fast)` printed on my prompt and then the window crashes immediately. I'm unsure whether this is coming from alacritty of zsh.

Here's how KDE is launching alacritty. Nothing special here.
```
$ head -n4 /usr/share/applications/Alacritty.desktop
[Desktop Entry]
Type=Application
TryExec=alacritty
Exec=alacritty
```

Launching from Konsole at least allows the terminal to be resized without crash, but running a terminal to launch a terminal is not particularly ergonomic!

Relevant section of the logs appears to be here:
```
[2021-11-30 12:42:49.448970257] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94268343571968))), event: ScaleFactorChanged { scale_factor: 2.0, new_inner_size: PhysicalSize { width: 4, height: 2 } } }
```
I've tried to debug this but I'm having a hard time figuring out why `winit` decides the window should be so small!

I'm running on a 4K display (3072x1728) and the scale factor is set to 125% - this has not changed...
Changing the scale factor to 100% actually results in a 2x1 window :sob: so this doesn't appear to be DPI related.

### System

OS: Fedora 35
Version: `alacritty 0.9.0`
Linux/BSD: KDE Plasma 5.23.3, kwin-wayland

I've also tried `alacritty` from master and I have the same issue.

### Logs

```
Created log file at "/tmp/Alacritty-30635.log"
[2021-11-30 12:42:49.366702022] [INFO ] [alacritty] Welcome to Alacritty
[2021-11-30 12:42:49.366775072] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/dave/.alacritty.yml"
[2021-11-30 12:42:49.378585513] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 12:42:49.379664791] [DEBUG] [alacritty] Estimated DPR: 1
[2021-11-30 12:42:49.379684993] [DEBUG] [alacritty] Estimated window size: None
[2021-11-30 12:42:49.379692799] [DEBUG] [alacritty] Estimated cell size: 9 x 19
[2021-11-30 12:42:49.420633857] [INFO ] [alacritty] Device pixel ratio: 2
[2021-11-30 12:42:49.427440655] [INFO ] [alacritty] Initializing glyph cache...
[2021-11-30 12:42:49.428862018] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 12:42:49.430823877] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 12:42:49.432542682] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 12:42:49.434257163] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 12:42:49.444924016] [INFO ] [alacritty] ... finished initializing glyph cache in 0.017447762s
[2021-11-30 12:42:49.444987696] [INFO ] [alacritty] Cell size: 18 x 38
[2021-11-30 12:42:49.444997281] [INFO ] [alacritty] Padding: 0 x 0
[2021-11-30 12:42:49.445003270] [INFO ] [alacritty] Width: 1600, Height: 1200
[2021-11-30 12:42:49.445973382] [INFO ] [alacritty] PTY dimensions: 31 x 88
[2021-11-30 12:42:49.448853849] [INFO ] [alacritty] Initialisation complete
[2021-11-30 12:42:49.448934771] [INFO ] [alacritty] glutin event: NewEvents(Init)
[2021-11-30 12:42:49.448970257] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94268343571968))), event: ScaleFactorChanged { scale_factor: 2.0, new_inner_size: PhysicalSize { width: 4, height: 2 } } }
[2021-11-30 12:42:49.449016986] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94268343571968))), event: Resized(PhysicalSize { width: 4, height: 2 }) }
[2021-11-30 12:42:49.449029938] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.449036422] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94268343571968))))
[2021-11-30 12:42:49.449042806] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.454496566] [INFO ] [alacritty] Font size changed to Size(22) with DPR of 2
[2021-11-30 12:42:49.461630520] [INFO ] [alacritty] Cell size: 18 x 38
[2021-11-30 12:42:49.461667403] [DEBUG] [alacritty_terminal] New num_cols is 2 and num_lines is 1
[2021-11-30 12:42:49.461755848] [INFO ] [alacritty] Padding: 0 x 0
[2021-11-30 12:42:49.461764943] [INFO ] [alacritty] Width: 4, Height: 2
[2021-11-30 12:42:49.462432094] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2283, tv_nsec: 794188460 }, requested_resume: None })
[2021-11-30 12:42:49.462452564] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.462460620] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94268343571968))))
[2021-11-30 12:42:49.462468543] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.463340106] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2283, tv_nsec: 795095961 }, requested_resume: None })
[2021-11-30 12:42:49.463389617] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94268343571968))), event: Focused(true) }
[2021-11-30 12:42:49.463425584] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94268343571968))), event: ModifiersChanged((empty)) }
[2021-11-30 12:42:49.463444223] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.463455814] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94268343571968))))
[2021-11-30 12:42:49.463464606] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.476801245] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2283, tv_nsec: 808556398 }, requested_resume: None })
[2021-11-30 12:42:49.476854340] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.476865278] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.477288462] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2283, tv_nsec: 809044996 }, requested_resume: None })
[2021-11-30 12:42:49.477307321] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.477317440] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.477490525] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2283, tv_nsec: 809247323 }, requested_resume: None })
[2021-11-30 12:42:49.477502357] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.477510261] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.513196638] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2283, tv_nsec: 844946348 }, requested_resume: None })
[2021-11-30 12:42:49.513316988] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.513330161] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.718382400] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 50136995 }, requested_resume: None })
[2021-11-30 12:42:49.718439151] [INFO ] [alacritty] glutin event: UserEvent(Terminal(Wakeup))
[2021-11-30 12:42:49.718458625] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.718471619] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.718860266] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 50616459 }, requested_resume: None })
[2021-11-30 12:42:49.718893851] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.718909036] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.719727579] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 51483680 }, requested_resume: None })
[2021-11-30 12:42:49.719763355] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.719781044] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.739058866] [DEBUG] [alacritty_terminal] [unhandled osc_dispatch]: [['1',],['~','/','d','e','v','/','a','l','a','c','r','i','t','t','y',],] at line 947
[2021-11-30 12:42:49.739099425] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 70855683 }, requested_resume: None })
[2021-11-30 12:42:49.739120210] [INFO ] [alacritty] glutin event: UserEvent(Terminal(Title(dave@dave-fedora: ~/dev/alacritty)))
[2021-11-30 12:42:49.739128563] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.739133748] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.739159997] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 70916925 }, requested_resume: None })
[2021-11-30 12:42:49.739167652] [INFO ] [alacritty] glutin event: UserEvent(Terminal(Wakeup))
[2021-11-30 12:42:49.739173286] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.739179766] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.739356433] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 71113208 }, requested_resume: None })
[2021-11-30 12:42:49.739368379] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.739377535] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.739554620] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 71311137 }, requested_resume: None })
[2021-11-30 12:42:49.739579564] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.739590349] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:49.742880091] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 74633684 }, requested_resume: None })
[2021-11-30 12:42:49.742953317] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:49.742965129] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.109351729] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 441105935 }, requested_resume: None })
[2021-11-30 12:42:50.109389454] [INFO ] [alacritty] glutin event: UserEvent(Terminal(Wakeup))
[2021-11-30 12:42:50.109398112] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.109406359] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.109652296] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 441409047 }, requested_resume: None })
[2021-11-30 12:42:50.109668688] [INFO ] [alacritty] glutin event: UserEvent(Terminal(Wakeup))
[2021-11-30 12:42:50.109678962] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.109684788] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.109903987] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 441660532 }, requested_resume: None })
[2021-11-30 12:42:50.109919864] [INFO ] [alacritty] glutin event: UserEvent(Terminal(Wakeup))
[2021-11-30 12:42:50.109927029] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.109932368] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.110350627] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 442107266 }, requested_resume: None })
[2021-11-30 12:42:50.110366952] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.110379457] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.110538229] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 442294922 }, requested_resume: None })
[2021-11-30 12:42:50.110579944] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.110585931] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.110735319] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 442492042 }, requested_resume: None })
[2021-11-30 12:42:50.110745691] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.110751073] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:50.125081223] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2284, tv_nsec: 456836688 }, requested_resume: None })
[2021-11-30 12:42:50.125122786] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:50.125129651] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:53.604334842] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2287, tv_nsec: 936078874 }, requested_resume: None })
[2021-11-30 12:42:53.604611936] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94268343571968))), event: Focused(false) }
[2021-11-30 12:42:53.604678920] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:53.604716421] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94268343571968))))
[2021-11-30 12:42:53.604758567] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:53.607691096] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2287, tv_nsec: 939446269 }, requested_resume: None })
[2021-11-30 12:42:53.607759699] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:53.607772242] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:53.607973977] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2287, tv_nsec: 939729918 }, requested_resume: None })
[2021-11-30 12:42:53.608011188] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:53.608027140] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 12:42:53.625452819] [INFO ] [alacritty] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 2287, tv_nsec: 957202850 }, requested_resume: None })
[2021-11-30 12:42:53.625608426] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 12:42:53.625629103] [INFO ] [alacritty] glutin event: RedrawEventsCleared
```

**Comment by chrisduerr** [comment]
Known issue, should be fixed on master.

**Comment by dave-tucker** [comment]
> I've also tried alacritty from master and I have the same issue

HEAD of my checkout is 8681f710

```
cargo run --bin alacritty -- -vv --print-events                                                                           ✔  10131  17:15:57
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/alacritty -vv --print-events`
Created log file at "/tmp/Alacritty-122994.log"
[2021-11-30 17:15:59.733796325] [INFO ] [alacritty] Configuration files loaded from:
                                                      "/home/dave/.alacritty.yml"
[2021-11-30 17:15:59.743880392] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 17:15:59.744940455] [DEBUG] [alacritty] Estimated DPR: 1
[2021-11-30 17:15:59.744987193] [DEBUG] [alacritty] Estimated window size: None
[2021-11-30 17:15:59.745012237] [DEBUG] [alacritty] Estimated cell size: 9 x 19
[2021-11-30 17:15:59.792193223] [INFO ] [alacritty] Device pixel ratio: 2
[2021-11-30 17:15:59.799424829] [INFO ] [alacritty] Initializing glyph cache...
[2021-11-30 17:15:59.800988892] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 17:15:59.803078375] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 17:15:59.804954043] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Regular, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 17:15:59.806831348] [DEBUG] [crossfont] Loaded Face Face { ft_face: Font Face: Bold, load_flags: NO_BITMAP | TARGET_LIGHT, render_mode: "Normal", lcd_filter: 1 }
[2021-11-30 17:15:59.829848036] [INFO ] [alacritty] ... finished initializing glyph cache in 0.030305988s
[2021-11-30 17:15:59.829985311] [INFO ] [alacritty] Cell size: 18 x 38
[2021-11-30 17:15:59.830041156] [INFO ] [alacritty] Padding: 0 x 0
[2021-11-30 17:15:59.830066793] [INFO ] [alacritty] Width: 1600, Height: 1200
[2021-11-30 17:15:59.839381872] [INFO ] [alacritty] PTY dimensions: 31 x 88
[2021-11-30 17:15:59.842135185] [INFO ] [alacritty] Initialisation complete
[2021-11-30 17:15:59.842254648] [INFO ] [alacritty] glutin event: NewEvents(Init)
[2021-11-30 17:15:59.842347144] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94424943529216))), event: ScaleFactorChanged { scale_factor: 2.0, new_inner_size: PhysicalSize { width: 4, height: 2 } } }
[2021-11-30 17:15:59.842443995] [INFO ] [alacritty] glutin event: WindowEvent { window_id: WindowId(Wayland(WindowId(94424943529216))), event: Resized(PhysicalSize { width: 4, height: 2 }) }
[2021-11-30 17:15:59.842517907] [INFO ] [alacritty] glutin event: MainEventsCleared
[2021-11-30 17:15:59.842583919] [INFO ] [alacritty] glutin event: RedrawRequested(WindowId(Wayland(WindowId(94424943529216))))
[2021-11-30 17:15:59.842643715] [INFO ] [alacritty] glutin event: RedrawEventsCleared
[2021-11-30 17:15:59.847901109] [INFO ] [alacritty] Font size changed to Size(22) with DPR of 2
[2021-11-30 17:15:59.868838679] [INFO ] [alacritty] Cell size: 18 x 38
[2021-11-30 17:15:59.868949066] [DEBUG] [alacritty_terminal] New num_cols is 2 and num_lines is 1
[2021-11-30 17:15:59.869120931] [INFO ] [alacritty] Padding: 0 x 0
[2021-11-30 17:15:59.869150586] [INFO ] [alacritty] Width: 4, Height: 2
```

I still see the problem described.

**Comment by chrisduerr** [comment]
It's possible that the specific change hasn't propagated through yet. But it was fixed in an upstream dependency. Just a matter of waiting for an update now.
