### ISSUE TITLE
Alacritty started crashing (segmentation fault) when seeing emoji

### ISSUE THREAD

**Issue by jplatte** [alacritty/alacritty#6727]
As of some time today, alacritty crashes for me whenever it tries to display an emoji. This can be triggered as easily as just pasting an emoji into it. It seems like this is related to a C dependency since it worked before and I didn't upgrade alacritty; however I don't see any other programs crashing. I upgraded a few font-related things today:

```
[2023-02-22T08:29:59+0100] [ALPM] upgraded harfbuzz (7.0.0-1 -> 7.0.1-1)
[2023-02-22T08:29:59+0100] [ALPM] upgraded harfbuzz-icu (7.0.0-1 -> 7.0.1-1)
[2023-02-22T08:29:59+0100] [ALPM] upgraded lib32-harfbuzz (7.0.0-1 -> 7.0.1-1)
[2023-02-22T08:29:59+0100] [ALPM] upgraded pango (1:1.50.12-1 -> 1:1.50.13-1)
[2023-02-22T08:29:59+0100] [ALPM] upgraded lib32-pango (1:1.50.12-1 -> 1:1.50.13-1)
[2023-02-22T08:30:00+0100] [ALPM] upgraded libibus (1.5.27-1 -> 1.5.28-1)
[2023-02-22T08:30:00+0100] [ALPM] upgraded libxmlb (0.3.10-1 -> 0.3.11-1)
```

However, a friend with another arch installation says he can't reproduce so there seems to be something setup specific to it as well. If somebody has capacity to look into this, let me know what extra information you need.

### System

OS: Linux
Version: alacritty 0.11.0 (8dbaa0bb)
DE: sway (wayland)

### Logs

```
[1]    106597 segmentation fault (core dumped)  alacritty
```

**Comment by kchibisov** [comment]
From the font stack with use freetype and fontconfig(nothing more). What I think is that freetype depends on harfbuzz and something changed in regards to it.

I'd suggest to try downgrading harfbuzz.

**Comment by kchibisov** [comment]
Closing, since we don't depend on harfbuzz directly and there's no clear stacktrace pointing out into alacritty.

**Comment by jplatte** [comment]
I did, that doesn't change anything unfortunately. Since you mentioned a stacktrace, the next step would be to build alacritty in debug mode and run it through a debugger to see where it crashes exactly?

**Comment by kchibisov** [comment]
you can provide at least something from the coredumpctl. it should show at least the libs.

**Comment by kchibisov** [comment]
If you can repro under the debug build it'll help as well, but it's likely not our issue. Likely just arch broke. Especially given that freetype wasn't rebuild on arch after harfbuzz update, because those cycle dep on each other.

**Comment by jplatte** [comment]
Here's what `coredumpctl dump <PID>` outputs, alongside a ~138MB dump file:

```
           PID: 125337 (alacritty)
           UID: 1000 (jplatte)
           GID: 1000 (jplatte)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-02-22 11:58:27 CET (1min 34s ago)
  Command Line: alacritty
    Executable: /usr/bin/alacritty
 Control Group: /user.slice/user-1000.slice/session-4.scope
          Unit: session-4.scope
         Slice: user-1000.slice
       Session: 4
     Owner UID: 1000 (jplatte)
       Boot ID: 2660b3d6c31641af812f6ef1f5e45317
    Machine ID: ef884759d4f442ea8f294aa48729af38
      Hostname: jp-desktop
       Storage: /var/lib/systemd/coredump/core.alacritty.1000.2660b3d6c31641af812f6ef1f5e45317.125337.1677063507000000.zst (present)
  Size on Disk: 3.4M
       Message: Process 125337 (alacritty) of user 1000 dumped core.

                Stack trace of thread 125337:
                #0  0x00007fc91accf8b8 n/a (libfreetype.so.6 + 0x348b8)
                #1  0x00007fc91acaf154 FT_Load_Glyph (libfreetype.so.6 + 0x14154)
                #2  0x000055eec96bd7f4 n/a (alacritty + 0x29c7f4)
                #3  0x000055eec95f5848 n/a (alacritty + 0x1d4848)
                #4  0x000055eec9537723 n/a (alacritty + 0x116723)
                #5  0x000055eec94b6522 n/a (alacritty + 0x95522)
                #6  0x000055eec96189a2 n/a (alacritty + 0x1f79a2)
                #7  0x000055eec94f20d5 n/a (alacritty + 0xd10d5)
                #8  0x000055eec958b67e n/a (alacritty + 0x16a67e)
                #9  0x000055eec94ee8d4 n/a (alacritty + 0xcd8d4)
                #10 0x000055eec95ac429 n/a (alacritty + 0x18b429)
                #11 0x000055eec95c4693 n/a (alacritty + 0x1a3693)
                #12 0x000055eec95a4057 n/a (alacritty + 0x183057)
                #13 0x00007fc91a980790 n/a (libc.so.6 + 0x23790)
                #14 0x00007fc91a98084a __libc_start_main (libc.so.6 + 0x2384a)
                #15 0x000055eec9493485 n/a (alacritty + 0x72485)

                Stack trace of thread 125338:
                #0  0x00007fc91aa5d0dd syscall (libc.so.6 + 0x1000dd)
                #1  0x000055eec97ce855 n/a (alacritty + 0x3ad855)
                #2  0x000055eec96f4466 n/a (alacritty + 0x2d3466)
                #3  0x000055eec96f518a n/a (alacritty + 0x2d418a)
                #4  0x000055eec97fb435 n/a (alacritty + 0x3da435)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125342:
                #0  0x00007fc91aa29db5 clock_nanosleep (libc.so.6 + 0xccdb5)
                #1  0x00007fc91aa2e987 __nanosleep (libc.so.6 + 0xd1987)
                #2  0x000055eec97b2659 n/a (alacritty + 0x391659)
                #3  0x000055eec97c2fec n/a (alacritty + 0x3a1fec)
                #4  0x000055eec97a7d33 n/a (alacritty + 0x386d33)
                #5  0x000055eec97fb435 n/a (alacritty + 0x3da435)
                #6  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #7  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125339:
                #0  0x00007fc91aa651b6 epoll_wait (libc.so.6 + 0x1081b6)
                #1  0x000055eec96d53a5 n/a (alacritty + 0x2b43a5)
                #2  0x000055eec96da366 n/a (alacritty + 0x2b9366)
                #3  0x000055eec96f4ed6 n/a (alacritty + 0x2d3ed6)
                #4  0x000055eec96f5897 n/a (alacritty + 0x2d4897)
                #5  0x000055eec97fb435 n/a (alacritty + 0x3da435)
                #6  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #7  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125345:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125340:
                #0  0x00007fc91aa5d0dd syscall (libc.so.6 + 0x1000dd)
                #1  0x000055eec97f6994 n/a (alacritty + 0x3d5994)
                #2  0x000055eec95b6290 n/a (alacritty + 0x195290)
                #3  0x000055eec954429b n/a (alacritty + 0x12329b)
                #4  0x000055eec97fb435 n/a (alacritty + 0x3da435)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125346:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125351:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125344:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125347:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125343:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125349:
                #0  0x00007fc91aa651b6 epoll_wait (libc.so.6 + 0x1081b6)
                #1  0x000055eec96d53a5 n/a (alacritty + 0x2b43a5)
                #2  0x000055eec95b8fea n/a (alacritty + 0x197fea)
                #3  0x000055eec9544847 n/a (alacritty + 0x123847)
                #4  0x000055eec97fb435 n/a (alacritty + 0x3da435)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125353:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125352:
                #0  0x00007fc91a9df766 n/a (libc.so.6 + 0x82766)
                #1  0x00007fc91a9e1f90 pthread_cond_wait (libc.so.6 + 0x84f90)
                #2  0x00007fc90250c49e n/a (radeonsi_dri.so + 0x10c49e)
                #3  0x00007fc9024bc86c n/a (radeonsi_dri.so + 0xbc86c)
                #4  0x00007fc90250c3cc n/a (radeonsi_dri.so + 0x10c3cc)
                #5  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #6  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)

                Stack trace of thread 125341:
                #0  0x00007fc91aa67168 accept4 (libc.so.6 + 0x10a168)
                #1  0x000055eec95b1785 n/a (alacritty + 0x190785)
                #2  0x000055eec9543ce3 n/a (alacritty + 0x122ce3)
                #3  0x000055eec97fb435 n/a (alacritty + 0x3da435)
                #4  0x00007fc91a9e2bb5 n/a (libc.so.6 + 0x85bb5)
                #5  0x00007fc91aa64d90 n/a (libc.so.6 + 0x107d90)
                ELF object binary architecture: AMD x86-64
```

**Comment by kchibisov** [comment]
Yeah, it's freetype crashing. I'd suggest to collect the stack trace from freetype and report to them. It seems like they've changed something around colored fonts.

https://gitlab.freedesktop.org/freetype/freetype/-/issues/?sort=created_date&state=opened&first_page_size=20


Would suggest to get debug info and try to downgrade the freetype.

**Comment by kchibisov** [comment]
@chrisduerr given that you're also on arch btw, could you repro that with some emoji font. Be aware that you'd need freetype 2.13.0 which reached arch repos like a week ago.

**Comment by kchibisov** [comment]
@jplatte oh, also, could you try alacritty master, there might be a change in some handling of fonts?

**Comment by jplatte** [comment]
So it's fixed on alacritty 0.13.0-dev (79ea8b94). It fails to render the emoji now, but at least it doesn't crash. I'll keep running this version for now, thanks!

**Comment by kchibisov** [comment]
@jplatte what emoji font are you using? Also, if you downgrade freetype does it change anything?

The thing I've fixed wasn't a crash in the first place, as I remember.

**Comment by jplatte** [comment]
Yes, downgrading `freetype2` to `2.12.1-1` also fixes the crash, though many emoji still fail to render, same as on alacritty-git + freetype 2.13.

**Comment by jplatte** [comment]
I have a few different emoji fonts installed, and I have font-config set up to not use Noto Color Emoji. Some Emoji that do render in alacritty seem to be using the Noto B/W font, but others are still colored, maybe using EmojiOne (a pretty old version I have installed).

**Comment by kchibisov** [comment]
Ah, we only work with `Noto Color Emoji` now, if you want emojis in the terminal, you should use it. As well as prepend it in the fontconfig rules, so it fallbacks after your main font.

JoyPixels may also work, but they might not include all emojis.

**Comment by jplatte** [comment]
Yeah, putting JoyPixels in the `fonts.conf` made everything work on latest freetype + release version of alacritty: https://github.com/jplatte/dotfiles/commit/35dbf01988d0d71da12bbc130d7da7215fcec7f5

**Comment by kchibisov** [comment]
duplicate of https://github.com/alacritty/alacritty/issues/6432
