### ISSUE TITLE
Delayed prompt display in Alacritty when using touchpad

### ISSUE THREAD

**Issue by hnsstrk** [alacritty/alacritty#7201]
### System

- **OS:** Linux Mint 21.2 x86_64  
- **Version:** alacritty 0.13.0-dev (8eed1722)  
- **Linux/BSD:** X11  

### Logs

[events.log](https://github.com/alacritty/alacritty/files/12545993/events.log)

**Font/Terminal size:**  
- Window scale factor: 2
- Cell size: 18 x 36
- Padding: 0 x 0
- Width: 1440, Height: 1080
- PTY dimensions: 30 x 80

**Keyboard and bindings:** The `events.log` has been created and can be attached if required.

### Issue Description

**Hardware:** Host: MacBookPro11,3 1.0

When launching Alacritty, the prompt only appears immediately when the cursor is inside the Alacritty window. This behavior seems to occur only when the touchpad has been used. If a mouse is used, this behavior does not occur.

**Comment by chrisduerr** [comment]
Could you share the output of `alacritty -vvv` with and without this issue? Only up until the window is created, so no logs after the prompt appeared.

Also what do you mean by "immediately"? Does the prompt just take some time to pop up, or does it require user interaction?

**Comment by hnsstrk** [comment]
I've tested this further.
It seems my initial observation wasn't entirely accurate.
When I launch Alacritty, I often see an empty window. The prompt only appears when the mouse is moved over the active window or a key is pressed. The prompt also appears when the Alacritty window becomes inactive.
In the video, I'm using p10k, but I've also disabled it for testing purposes. However, this didn't change the behavior.
Sometimes I can start Alacritty and immediately see a prompt, but I can't reliably reproduce this.

https://www.youtube.com/watch?v=7E5ExLINw9E

[alacritty_noprompt.log](https://github.com/alacritty/alacritty/files/12548132/alacritty_noprompt.log)


[alacritty_prompt.log](https://github.com/alacritty/alacritty/files/12548214/alacritty_prompt.log)

**Comment by chrisduerr** [comment]
This is GNOME/X11 I'd assume? Could you try Wayland? It looks like it doesn't track the terminal damage for the last frame.

**Comment by hnsstrk** [comment]
I'm currently using Linux Mint with the Cinnamon Desktop (X11).

I'm not at home right now and only have an older laptop with me, which might make things a bit cumbersome. However, I can try to get another distribution running to test under both X11 and Wayland.
Would it be sufficient to test this in a VM, or would it be better for me to examine it directly on the hardware?

**Comment by chrisduerr** [comment]
>  Would it be sufficient to test this in a VM, or would it be better for me to examine it directly on the hardware?

VM is going to add a ton of variables, but if you reproduce it in a VM that would work fine. But I doubt you'll be able to reproduce this on Wayland.

I'm mainly curious if this can be reproduced on the exact same system with Wayland, since switching on GNOME should be relatively simple.

This is either a driver bug, or Alacritty isn't redrawing properly after the terminal was written to. Could you share the output of `alacritty -vvv --print-events`, both the text which appears at startup, and the text that appears once it fixes itself. To minimize extra log messages I recommend not using the mouse.

**Comment by hnsstrk** [comment]
I've looked into it, but I couldn't figure out how to get Wayland running on Linux Mint. I'm trying to find a suitable distro that will work on my older hardware. However, this might take me a few days.

**Comment by hnsstrk** [comment]
I had some time over the weekend to set up Fedora 38 and briefly observed the behavior under both Wayland and X11. Interestingly, the issue doesn't occur on Wayland, but I was able to reproduce it on X11. If everything goes smoothly, I should be able to provide the logs either tomorrow or the day after. Thanks for your patience!

**Comment by chrisduerr** [comment]
Do you ever have issues where input isn't rendered immediately after pressing the key?

Also does every log level fix this? So even `alacritty -v`?

**Comment by vsl-iil** [comment]
I encountered the same issue today. Running commands like neofetch, git push, etc. make it seem that they stalled in the end, but if I move a cursor (I'm using touchpad too) or press a key, only then the bash prompt appears. Xterm doesn't have the same issue, so I'm fairy certain it is some kind of Alacritty bug.
And yes, if I run `alacritty -vvv`, the bug dissapears. In fact, it is quite inconsistent, but I had more success in reproducing it when running autocompleted commands or typing them manually, than getting them from bash history.
The log from `alacritty -v` try doesn't show anything useful:
```
[0.000001155s] [INFO ] [alacritty] Welcome to Alacritty
[0.000085011s] [INFO ] [alacritty] Version 0.13.0-dev (34b5dbac)
[0.000109431s] [INFO ] [alacritty] Running on X11
[0.000244608s] [INFO ] [alacritty_config_derive] No config file found; using default
[0.003606480s] [INFO ] [alacritty] Using GLX 1.4
[0.086337529s] [INFO ] [alacritty] Window scale factor: 1.5
[0.104483897s] [INFO ] [alacritty] Running on Mesa Intel(R) UHD Graphics (JSL)
[0.104552069s] [INFO ] [alacritty] OpenGL version 4.6 (Core Profile) Mesa 23.1.7-arch1.1, shader_version 4.60
[0.104558578s] [INFO ] [alacritty] Using OpenGL 3.3 renderer
[0.144401970s] [INFO ] [alacritty] Cell size: 13 x 27
[0.144464236s] [INFO ] [alacritty] Padding: 0 x 0
[0.144471029s] [INFO ] [alacritty] Width: 800, Height: 600
[0.156835331s] [INFO ] [alacritty] PTY dimensions: 22 x 61
[0.161001384s] [INFO ] [alacritty] Initialisation complete
[0.183331252s] [INFO ] [alacritty] Padding: 0 x 0
[0.183384738s] [INFO ] [alacritty] Width: 1054, Height: 1056
```

OS: Artix Linux x86_64
WM: dwm 6.4
GPU: Intel JasperLake [UHD Graphics]

**Comment by chrisduerr** [comment]
@vsl-iil If you move the mouse the bug disappears, even when not actually clicking? So just hovering the mouse over the window?

**Comment by vsl-iil** [comment]
Yes, the prompt appears if I move a mouse inside the terminal window.

**Comment by chrisduerr** [comment]
Can you disable all hints and try again if moving the mouse still updates things?

**Comment by chrisduerr** [comment]
@kchibisov sounds like it might be related to the winit update?

**Comment by kchibisov** [comment]
@hnsstrk could you bisect? Since there were multiple updates to winit, so it's hard to say what exactly broke.

**Comment by hnsstrk** [comment]
I truly appreciate the swift responses and suggestions. However, due to some personal challenges I'm facing at the moment, I'm currently unable to perform a bisect or conduct further tests. I hope the issue can still be resolved, and I'll aim to contribute more actively once circumstances allow. Thank you for your understanding and continued work on Alacritty.

**Comment by tbozan** [comment]
Can confirm, commit `bbc02004` is ok, commit `a1898618` fails to update window contents.
(latest kernel, xorg and mesa)

**Comment by kchibisov** [comment]
@tbozan could you apply this patch and try with `alacritty --print-events`?

```diff
diff --git a/alacritty/src/display/window.rs b/alacritty/src/display/window.rs
index aef6e1b5..e3c2f07d 100644
--- a/alacritty/src/display/window.rs
+++ b/alacritty/src/display/window.rs
@@ -238,8 +238,10 @@ impl Window {
 
     #[inline]
     pub fn request_redraw(&mut self) {
+        println!("[ALACRITTY] Trying to request a redraw");
         if !self.requested_redraw {
             self.requested_redraw = true;
+            println!("[ALACRITTY] Redraw requested");
             self.window.request_redraw();
         }
     }
diff --git a/alacritty/src/window_context.rs b/alacritty/src/window_context.rs
index 332bdcd9..e42532af 100644
--- a/alacritty/src/window_context.rs
+++ b/alacritty/src/window_context.rs
@@ -391,6 +391,7 @@ impl WindowContext {
             self.display.window.request_redraw();
         }
 
+        println!("[ALACRITTY] Drawing the window");
         // Redraw the window.
         let terminal = self.terminal.lock();
         self.display.draw(

```

If `--print-events` fixes it, try just this patch. Nothing should be fixed by any of these, it's simply to log and troubleshoot.

**Comment by kchibisov** [comment]
Could you try https://github.com/alacritty/alacritty/pull/7220 ? I can't reproduce the issue, but maybe this patch will resolve it, since one part of the API we use was sort of broken upstream on X11.

**Comment by bezvez** [comment]
@kchibisov `--print-events` + first patch with printlns still fails to update screen. Log when problem happens:
```
[ALACRITTY] Trying to request a redraw
[ALACRITTY] Redraw requested
[152.798321489s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(56623107)))
[ALACRITTY] Drawing the window
[152.798989305s] [INFO ] [alacritty] winit event: AboutToWait
[152.798998225s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26230, tv_nsec: 258931421 }, requested_resume: Some(Instant { tv_sec: 26230, tv_nsec: 272985907 }) })
[152.799003145s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799006415s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799010345s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799014725s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799018775s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799022775s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799026215s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799029045s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799033815s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799037775s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799040885s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799043645s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799048095s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799052555s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799056255s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799061685s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799065635s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799069865s] [INFO ] [alacritty] winit event: AboutToWait
[152.799082265s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26230, tv_nsec: 259009251 }, requested_resume: Some(Instant { tv_sec: 26230, tv_nsec: 272985907 }) })
[152.799087765s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799091255s] [INFO ] [alacritty] winit event: AboutToWait
[152.800235239s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26230, tv_nsec: 259029751 }, requested_resume: Some(Instant { tv_sec: 26230, tv_nsec: 272985907 }) })
[152.800275138s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.800286878s] [INFO ] [alacritty] winit event: AboutToWait
```

7220 applied over `77aa9f42` works 🎉

**Comment by tbozan** [comment]
@kchibisov --print-events + first patch with printlns still fails to update screen. Log when problem happens:
```
[ALACRITTY] Trying to request a redraw
[ALACRITTY] Redraw requested
[152.798321489s] [INFO ] [alacritty] winit event: RedrawRequested(WindowId(WindowId(56623107)))
[ALACRITTY] Drawing the window
[152.798989305s] [INFO ] [alacritty] winit event: AboutToWait
[152.798998225s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26230, tv_nsec: 258931421 }, requested_resume: Some(Instant { tv_sec: 26230, tv_nsec: 272985907 }) })
[152.799003145s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799006415s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799010345s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799014725s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799018775s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799022775s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799026215s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799029045s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799033815s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799037775s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799040885s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799043645s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799048095s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799052555s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799056255s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799061685s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799065635s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799069865s] [INFO ] [alacritty] winit event: AboutToWait
[152.799082265s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26230, tv_nsec: 259009251 }, requested_resume: Some(Instant { tv_sec: 26230, tv_nsec: 272985907 }) })
[152.799087765s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.799091255s] [INFO ] [alacritty] winit event: AboutToWait
[152.800235239s] [INFO ] [alacritty] winit event: NewEvents(WaitCancelled { start: Instant { tv_sec: 26230, tv_nsec: 259029751 }, requested_resume: Some(Instant { tv_sec: 26230, tv_nsec: 272985907 }) })
[152.800275138s] [INFO ] [alacritty] winit event: UserEvent(Event { window_id: Some(WindowId(WindowId(56623107))), payload: Terminal(Wakeup) })
[152.800286878s] [INFO ] [alacritty] winit event: AboutToWait
```

7220 applied over 77aa9f42 works 🎉

**Comment by kchibisov** [comment]
@tbozan I'm not sure how clear was it, but the first patch shouldn't fix anything. Just test #7220 in isolation then. If it fixes then it's good to know.

**Comment by tbozan** [comment]
Yeah, i know, i just thought you wanted the logs around those messages you added.
#7220 was applied on clean 77aa9f42, without your first patch.

**Comment by kchibisov** [comment]
Yeah, from what I can see it's correctly that it broke, since the timer is not firing, because it's based on timeout and timeouts are broken upstream, since there's no wakeup from them.
