### ISSUE TITLE
Clipboard stop working after S3 sleep/wake up cycle

### ISSUE THREAD

**Issue by ivan-volnov** [alacritty/alacritty#8001]
Clipboard stop working after S3 sleep/wake up cycle. It started right after updating to the last version.

![image](https://github.com/alacritty/alacritty/assets/51086293/2b54ab1f-a468-4364-931c-654cf8ab58c8)

### System

OS: FreeBSD 14
Version: alacritty 0.13.2
X11, bspwm, picom

### Logs

[369.860573796s] [WARN ] [alacritty] Unable to store text in clipboard: XCB - couldn't set atom: SendError { .. }

**Comment by concussious** [comment]
Hi, I am having the same issue on the FreeBSD 15-CURRENT (latest development branch).

**Comment by chrisduerr** [comment]
Does rebooting help?

**Comment by concussious** [comment]
> Does rebooting help?

Yes, but you don't need to go that far. A new alacrity window after resume from suspend has a working clipboard, including while the old one is still up, but any alacrity window that persists through a suspend/resume cycle cannot put anything into the clipboard.

**Comment by lmas** [comment]
Is this any helpful? I did a git bisect between v0.13.1 and v0.13.2 and found this:

```
# git bisect bad                                                                                                                                                                                                                                                                           
fc0455e310d87837b2d26e0f33c139b4660aa0d6 is the first bad commit
2024-03-19 02:20:53 +0100 fc0455e3 Christia.. Bump winit to 0.29.11
 CHANGELOG.md         |  4 ++++
 Cargo.lock           | 95 +++++++++++++++++------------------------------------------------------------------------------
 alacritty/Cargo.toml |  4 ++--
 3 files changed, 23 insertions(+), 80 deletions(-)

# rustc --version                                                                                                                                                                                                                                                                         
rustc 1.81.0

# uname -v
FreeBSD 14.2-RELEASE
```

Between the git bisect jumps I:

- ran `cargo build --release`
- executed the build and verified that I could select text
-  suspended my laptop and woke it up again
- tried text selection again in the still open terminal window and checked if I got `SendError` warning

Sad that it was just a package version bump. I don't know rust and don't know how to continue the investigation from this.

**Comment by kchibisov** [comment]
@lmas have you tried  0.14.0?

**Comment by lmas** [comment]
Tested 0.14.0 and 0.14.1-rc1, the error is still present unfortunately.

**Comment by kchibisov** [comment]
If you apply  

```diff
diff --git a/Cargo.lock b/Cargo.lock
index 23325812..b3b4e4ab 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -454,9 +454,9 @@ dependencies = [
 
 [[package]]
 name = "copypasta"
-version = "0.10.1"
+version = "0.10.0"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "deb85422867ca93da58b7f95fb5c0c10f6183ed6e1ef8841568968a896d3a858"
+checksum = "6d35364349bf9e9e1c3a035ddcb00d188d23a3c40c50244c03c27a99fc6a65ae"
 dependencies = [
  "clipboard-win",
  "objc",
@@ -780,6 +780,16 @@ version = "0.3.31"
 source = "registry+https://github.com/rust-lang/crates.io-index"
 checksum = "9e5c1b78ca4aae1ac06c48a526a655760685149f0d465d21f37abfe57ce075c6"
 
+[[package]]
+name = "gethostname"
+version = "0.3.0"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "bb65d4ba3173c56a500b555b532f72c42e8d1fe64962b518897f8959fae2c177"
+dependencies = [
+ "libc",
+ "winapi",
+]
+
 [[package]]
 name = "gethostname"
 version = "0.4.3"
@@ -1090,6 +1100,15 @@ dependencies = [
  "libc",
 ]
 
+[[package]]
+name = "memoffset"
+version = "0.7.1"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "5de893c32cde5f383baa4c04c5d6dbdd735cfd4a794b0debdb2bb1b421da5ff4"
+dependencies = [
+ "autocfg",
+]
+
 [[package]]
 name = "miniz_oxide"
 version = "0.8.0"
@@ -1151,6 +1170,18 @@ dependencies = [
  "jni-sys",
 ]
 
+[[package]]
+name = "nix"
+version = "0.26.4"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "598beaf3cc6fdd9a5dfb1630c2800c7acd31df7aaf0f565796fba2b53ca1af1b"
+dependencies = [
+ "bitflags 1.3.2",
+ "cfg-if",
+ "libc",
+ "memoffset",
+]
+
 [[package]]
 name = "notify"
 version = "6.1.1"
@@ -2304,6 +2335,15 @@ dependencies = [
  "windows-sys 0.59.0",
 ]
 
+[[package]]
+name = "winapi-wsapoll"
+version = "0.1.2"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "1eafc5f679c576995526e81635d0cf9695841736712b4e892f87abbe6fed3f28"
+dependencies = [
+ "winapi",
+]
+
 [[package]]
 name = "winapi-x86_64-pc-windows-gnu"
 version = "0.4.0"
@@ -2573,7 +2613,7 @@ dependencies = [
  "web-time",
  "windows-sys 0.52.0",
  "x11-dl",
- "x11rb",
+ "x11rb 0.13.1",
  "xkbcommon-dl",
 ]
 
@@ -2607,12 +2647,11 @@ dependencies = [
 
 [[package]]
 name = "x11-clipboard"
-version = "0.9.3"
+version = "0.8.1"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "662d74b3d77e396b8e5beb00b9cad6a9eccf40b2ef68cc858784b14c41d535a3"
+checksum = "b41aca1115b1f195f21c541c5efb423470848d48143127d0f07f8b90c27440df"
 dependencies = [
- "libc",
- "x11rb",
+ "x11rb 0.12.0",
 ]
 
 [[package]]
@@ -2626,6 +2665,19 @@ dependencies = [
  "pkg-config",
 ]
 
+[[package]]
+name = "x11rb"
+version = "0.12.0"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "b1641b26d4dec61337c35a1b1aaf9e3cba8f46f0b43636c609ab0291a648040a"
+dependencies = [
+ "gethostname 0.3.0",
+ "nix",
+ "winapi",
+ "winapi-wsapoll",
+ "x11rb-protocol 0.12.0",
+]
+
 [[package]]
 name = "x11rb"
 version = "0.13.1"
@@ -2633,12 +2685,21 @@ source = "registry+https://github.com/rust-lang/crates.io-index"
 checksum = "5d91ffca73ee7f68ce055750bf9f6eca0780b8c85eff9bc046a3b0da41755e12"
 dependencies = [
  "as-raw-xcb-connection",
- "gethostname",
+ "gethostname 0.4.3",
  "libc",
  "libloading",
  "once_cell",
  "rustix",
- "x11rb-protocol",
+ "x11rb-protocol 0.13.1",
+]
+
+[[package]]
+name = "x11rb-protocol"
+version = "0.12.0"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "82d6c3f9a0fb6701fab8f6cea9b0c0bd5d6876f1f89f7fada07e558077c344bc"
+dependencies = [
+ "nix",
 ]
 
 [[package]]
diff --git a/alacritty/Cargo.toml b/alacritty/Cargo.toml
index eff0b089..57d79ad5 100644
--- a/alacritty/Cargo.toml
+++ b/alacritty/Cargo.toml
@@ -26,7 +26,7 @@ version = "0.2.3-dev"
 ahash = { version = "0.8.6", features = ["no-rng"] }
 bitflags = "2.2.1"
 clap = { version = "4.2.7", features = ["derive", "env"] }
-copypasta = { version = "0.10.1", default-features = false }
+copypasta = { version = "=0.10.0", default-features = false }
 crossfont = "0.8.0"
 glutin = { version = "0.32.0", default-features = false, features = ["egl", "wgl"] }
 home = "0.5.5"

```

to the current master, does it work?

**Comment by lmas** [comment]
Yes! That patch worked great, no errors after suspend/wake.

**Comment by ivan-volnov** [comment]
In which version this has been fixed?

**Comment by matt-bsd** [comment]
Hello, I'm still experiencing this exact issue on FreeBSD14.2-RELEASE:

i~> freebsd-version -kru
14.2-RELEASE-p1
14.2-RELEASE-p1
14.2-RELEASE-p1
i~> alacritty --version
alacritty 0.15.0
i~>

**Comment by sgharms** [comment]
Here to say broken on a new build of FreeBSD 15.0-CURRENT.

**Comment by fmc000** [comment]
Still broken in 0.16.1 on FreeBSD 14.3-STABLE.

**Comment by vishwin** [comment]
This appears to have been introduced in quininer/x11-clipboard#46 via alacritty/copypasta#67. Another FreeBSD user (not on GitHub) suggests that our `poll()` is timing out after resume from S3.

Is this a problem on systems other than FreeBSD?

**Comment by ivan-volnov** [comment]
Still broken 0.16.1 on FreeBSD 15.0-RELEASE.
It happens strictly after S3 sleep/wake up cycle.

The similar issues happen on macOS: #8041 and Linux #6978

**Comment by ivan-volnov** [comment]
Can anybody upgrade x11-clipboard to the latest v0.9.3 in [alacritty/copypasta](https://github.com/alacritty/copypasta) and then build alacritty with it?

Or just try to undo https://github.com/alacritty/copypasta/pull/67 and try?

**Comment by ivan-volnov** [comment]
It seems we need only edit [Cargo.toml](https://github.com/alacritty/copypasta/blob/master/Cargo.toml) and change "0.9.1" "0.9.3" and then build

**Comment by ivan-volnov** [comment]
Thanks to Benjamin Jacobs for the patch he posted on https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=293600

This a step by step fix for alacritty 0.16.1 on FreeBSD:

`cd /usr/ports/x11/alacritty`

**files/patch-cargo-crates_x11-clipboard-0.9.3_Cargo.toml**
```patch
--- cargo-crates/x11-clipboard-0.9.3/Cargo.toml.orig	2026-03-20 05:31:38 UTC
+++ cargo-crates/x11-clipboard-0.9.3/Cargo.toml
@@ -59,3 +59,6 @@ features = ["xfixes"]
 [dependencies.x11rb]
 version = "0.13.0"
 features = ["xfixes"]
+
+[dependencies.errno]
+version = "0.3.14"
```


**patch-cargo-crates_x11-clipboard-0.9.3_src_run.rs**
```patch
--- cargo-crates/x11-clipboard-0.9.3/src/run.rs.orig	2026-03-20 05:33:01 UTC
+++ cargo-crates/x11-clipboard-0.9.3/src/run.rs
@@ -80,6 +80,9 @@ pub(crate) fn run(context: Arc<Context>, setmap: SetMa
             // Any negative value (-1 for example) means infinite timeout.
             let poll_res = libc::poll(&mut pollfds as *mut libc::pollfd, len as libc::nfds_t, -1);
             if poll_res < 0 {
+                if errno::errno().0 == libc::EINTR {
+                    continue;
+                }
                 // Error polling, can't continue
                 return;
             }
```
`make CARGO_BUILDDEP=any-version reinstall`

**Comment by vishwin** [comment]
#6978 seems unrelated to this, as it deals with tmux interactions. #8041 also not related because macOS doesn't use X in the same way as the other Unix-like systems do, thus `x11-clipboard` out of the equation.

With FreeBSD port maintainer hat, I don't intend on including this workaround at this time. I also don't intend on reverting quininer/x11-clipboard#46, which apparently introduced this issue, since it fixes arguably more important clipboard connection leakage.

> Can anybody upgrade x11-clipboard to the latest v0.9.3 in [alacritty/copypasta](https://github.com/alacritty/copypasta) and then build alacritty with it?
> 
> Or just try to undo [alacritty/copypasta#67](https://github.com/alacritty/copypasta/pull/67) and try?

The FreeBSD port has been using `x11-clipboard` 0.9.3 since before the current alacritty version.

To properly move this issue forward, the main item to investigate is comparing how `poll()` behaves after an S3 resume (Modern Standby/S0ix may be a different story) on Unix-like systems that use X, ie Linux, FreeBSD, etc. It will determine where the problem actually lies.

**Comment by orbitz** [comment]
Hello, just another FreeBSD user piping in saying I'm impacted by this change and a fix would be appreciated.
